### ISSUE TITLE
Relative paths do not work when using `npx lwc-codemod`

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc-codemod#24]
Maybe this is an issue with Volta/npx or something, but I'm seeing this error:

```bash
npx lwc-codemod shadow-to-light ./folder
```

```
Error: Directory is a file or does not exist: ./folder
    at runTransform (file:///Users/nlawson/.npm/_npx/5649e45054f57b8b/node_modules/lwc-codemod/transforms/runTransform.js:27:11)
    at async main (file:///Users/nlawson/.npm/_npx/5649e45054f57b8b/node_modules/lwc-codemod/transforms/index.js:10:3)
```

The workaround is to do:

```bash
npx lwc-codemod shadow-to-light $(pwd)/folder
```

Bizarrely, I don't run into this error if I execute the `.npm/_npx/5649e45054f57b8b/node_modules/lwc-codemod/transforms/cli.js` file directly.

**Comment by nolanlawson** [comment]
I can't reproduce anymore. Weird.
